### ISSUE TITLE
Administration tool (CLI)

### ISSUE THREAD

**Issue by lamyj** [lamyj/dopamine#2]
The dynamic configuration of Dopamine (i.e. everything stored in the main database) is currently manual: collections must be altered through MongoDB clients. In order to avoid mis-configurations and to improve user-friendliness, this should be done using a CLI tool akin to [doveadm](http://wiki2.dovecot.org/Tools/Doveadm).

Assuming the name of such a tool to be `dopamine-adm`, the available operations should be
- `authorization list`: list the authorization entries
- `authorization add <PRINCIPAL> <SERVICE> [DATASET_AS_JSON]`: add an authorization entry
- `authorization remove <PRINCIPAL> <SERVICE> [DATASET_AS_JSON]`: remove an authorization entry that matches _exactly_
- `application_entities list`: list the known application entities
- `application_entities add <AE_TITLE> <HOST> <PORT>`: add an application entity (cf. #1)
- `application_entities remove <AE_TITLE> <HOST> <PORT>`: remove an application entity (cf. #1)

**Comment by Lahaxe** [comment]
commit b44fc50030dbbb8d788304c165ed1fb9c2888f9e
